disabled_rules: # rule identifiers to exclude from running
    - trailing_whitespace
    - missing_docs
    - syntactic_sugar
opt_in_rules: # some rules are only opt-in
    - conditional_returns_on_newline
    - force_unwrapping
    - empty_count
    - vertical_whitespace
    - private_outlet
excluded: # paths to ignore during linting. Takes precedence over `included`.
    - Carthage
# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
    severity: warning # explicitly
line_length: 160
function_parameter_count:
    warning: 10
    error: 15
function_body_length:
    warning: 100
    error: 150
type_body_length:
    waring: 300
    error: 400
file_length:
    warning: 600
    error: 1200
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
    min_length: 4 # only warning
    max_length: # warning and error
        warning: 40
        error: 50
variable_name:
    min_length: # only min_length
        error: 4 # only error
    excluded: # excluded via string array
        - id
        - URL
        - url
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit)